name: Tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  integration_tests:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.x" # Version range or exact version of a Ruby version to use, using semvers version range syntax.
      - name: Install Gems
        run: bundle install
      - name: Build and Test
        run: bundle exec rake
